### ISSUE TITLE
0.49.2 Windows Java version 11.0.10 water tiles not loading in MM

### ISSUE THREAD

**Issue by deadduck866** [MegaMek/megamek#2917]
0.49.2 Windows Java version 11.0.10

Tiles for water are not loading and giving a bland hex with red cross
![image](https://user-images.githubusercontent.com/82244617/120934106-e6b6ed80-c6f4-11eb-968c-96b5efb0975f.png)

**Comment by SJuliez** [comment]
The images are there, at least online. Somehow they do not find their way into the download.

**Comment by Windchild292** [comment]
I have a theory that this is localized to MekHQ's nightlies, will test shortly

**Comment by neoancient** [comment]
The directory is named Structured_Water, not Structured_water.

**Comment by grylock666** [comment]
Just in case it has fallen under the table: this still persists as of the latest Gradle build #1403

**Comment by Windchild292** [comment]
Going to need build clarification @grylock666. Do you mean  https://github.com/MegaMek/mekhq/pull/2731, the force generator fallback pr, and specifically https://github.com/MegaMek/mekhq/actions/runs/984611358 ?

**Comment by grylock666** [comment]
What I meant was that in the download package Gradle build 1403 the issue with the non-existant depth 1 water tiles still exists. I guess the directory capitalization issue wasn't fixed correctly (or there was no time yet?). Just asking because the issue is considered closed.

**Comment by Windchild292** [comment]
It should be fixed, but I don't know what build you are talking about to check. We have three different sources of potential gradle builds, and I believe the one mentioned above is our only one at 1403.

**Comment by grylock666** [comment]
Ah, I understand your problem. It really has nothing to do with that specific build, I was just referencing the build number to provide a point in time for the error, i could just as well have stated a date or one of the nightlies. My point is simply: you can download any current dev package (for example i just downloaded the Nightly CI #444), the D1 water tiles are still not in there.

**Comment by Windchild292** [comment]
Ah, I'll reopen this then as what we believed to be a fix didn't fix it.

**Comment by HoneySkull** [comment]
It was noticed that structured water images are missing in the 0.49.3 MegaMek stand-alone download zip, but exist in the combined MekHQ 0.49.3 zip.  It seems like in the stand alone build, and atlas image is created and the source files are removed, but in the combined MekHQ build the atlas image AND source images are in the zip.  

Is it possible the stand alone distributable process, atlas generator, is removing the structured water files in the stand alone distribution?

Got the tip from a friend, I will try to confirm later.

**Comment by HoneySkull** [comment]
While building nightlies, several of the water tile images are being added to an atlas for structured water if they match standard hex size.  The build task to add these images to the atlas also deletes the source files from the build directory.  Several *.tileinc files reference these source image files by name and probably need to be there for the map to work correctly.  I'm trying a quick fix to exclude the "Structured_Water" tiles from the image atlas process - this may resolve the missing water tiles in the nightly builds.
