### ISSUE TITLE
[0.49.12] Environmental Specialist SPA not reducing penalties from high wind

### ISSUE THREAD

**Issue by Gribbly1** [MegaMek/megamek#4305]
Bundled Megamek with MekHQ 0.49.12
Windows 10, Java Version: 11.0.13

Environmental Specialist, CamOps p74
'Storm' wind conditions TO: AR p34

For example, a hover unit with the Wind version of the SPA turning while flanking is not receiving any benefit:
![image](https://user-images.githubusercontent.com/55139229/230803076-958ecb5c-95fb-4af0-9f70-d64c286b417a.png)

A mech with the same SPA also has the full penalty turning while running on pavement:
![image](https://user-images.githubusercontent.com/55139229/230803198-e6aefccf-8c9d-4f8a-a777-15192dcb1109.png)

Name: 'Test'

[test.sav.gz](https://github.com/MegaMek/megamek/files/11186667/test.sav.gz)

Rain and Snow appear to be working fine:
![image](https://user-images.githubusercontent.com/55139229/230803481-d26452c7-7088-4cdf-bf41-a1a65519a02f.png)

![image](https://user-images.githubusercontent.com/55139229/230803580-46224444-dc87-4338-bb7d-9540a5ad3cc4.png)

**Comment by Gribbly1** [comment]
Snow specialist isn't reducing the PSR penalty for snow laying on the ground, if that's within scope.

![image](https://user-images.githubusercontent.com/55139229/231444275-cbe06023-d8c1-47ad-a137-e639b296e100.png)

**Comment by pheonixstorm** [comment]
As for the snow, what is on the ground is a terrain feature and not part of the Snow weather. 

For the first I will have to take a look later today.

**Comment by Gribbly1** [comment]
That makes sense, it seemed worth checking for completeness.

**Comment by pheonixstorm** [comment]
I tried to load the save but nothing showed up, no units at all. Looking at the code though, everything should be working properly. Will start testing a few new games and see if I can reproduce and find the issue.

**Comment by Gribbly1** [comment]
[test.sav.gz](https://github.com/MegaMek/megamek/files/11239957/test.sav.gz)

Here's another save, 'test'.

**Comment by Gribbly1** [comment]
The Wind specialist works when it's raining _and_ windy (but not snowing or no precipitation).

![image](https://user-images.githubusercontent.com/55139229/232245214-c76586b0-023d-4c57-ba79-dbc069ef48e5.png)

**Comment by Gribbly1** [comment]
![image](https://github.com/MegaMek/megamek/assets/55139229/863e382d-55a1-4a2e-8af7-14d4cf8f2917)

[test.sav.gz](https://github.com/MegaMek/megamek/files/11560118/test.sav.gz)
save: test

Issue still present in 49.13

**Comment by pheonixstorm** [comment]
So as for Wind + Snowing... it doesn't affect much. Mechs only have a PSR check under heavy snow. Aero, WiGE, and VTOL are the only thing affected that would require a PSR.

**Comment by Gribbly1** [comment]
The 'Environmental Specialist Wind' SPA doesn't currently work for the Wind penalty when the only weather condition is high wind. This is the only thing that needs to be fixed, anything else is additional info only. 

If it is raining _and_ windy the _wind_ specialist then works for the _wind penalty only_ - but the wind SPA doesn't work for the wind penalty _unless it is also raining_ which should not be a factor for 'Environmental Specialist Wind'.

My comment about wind+snow was purely to show another bug example in contrast to wind+rain, for the wind penalty only and the wind SPA only, not a suggestion that it should work that way.

**Comment by pheonixstorm** [comment]
Pushing a fix for this now.
